package Frames;


import Frames.Login;
import Frames.ManageProduct;
import Frames.SignUp;
import Frames.BillingSystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BAPPY
 */
public class Features extends javax.swing.JFrame {
    
    private static String accountType;
    /**
     * Creates new form Features
     */
    public Features() {
        initComponents();
        setTitle("Features");
        this.setLocationRelativeTo(null);
        
        
    }
    
    public void setAccountType(String type)
    {
        accountType = type;
    }
    
    private String getAccountType()
    {
        return accountType;
    }
    
    public void accountIdentifier()
    {
        if(getAccountType().equals("User"))
        {
            createAccountButton.setEnabled(false);
            manageProductButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salesHistoryButton = new javax.swing.JButton();
        billingSystemButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        createAccountButton = new javax.swing.JButton();
        manageProductButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salesHistoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salesHistoryButton.setText("Sales History");
        salesHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesHistoryButtonActionPerformed(evt);
            }
        });
        salesHistoryButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salesHistoryButtonKeyPressed(evt);
            }
        });
        jPanel1.add(salesHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 166, 145, 51));

        billingSystemButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        billingSystemButton.setText("Billing System");
        billingSystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingSystemButtonActionPerformed(evt);
            }
        });
        billingSystemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                billingSystemButtonKeyPressed(evt);
            }
        });
        jPanel1.add(billingSystemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 145, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Options");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 196, -1));

        createAccountButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        createAccountButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                createAccountButtonKeyPressed(evt);
            }
        });
        jPanel1.add(createAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 145, 51));

        manageProductButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageProductButton.setText("Manage Product");
        manageProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductButtonActionPerformed(evt);
            }
        });
        manageProductButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manageProductButtonKeyPressed(evt);
            }
        });
        jPanel1.add(manageProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 166, -1, 51));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        BackButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackButtonKeyPressed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 98, 37));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/background.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductButtonActionPerformed
        // TODO add your handling code here:
        ManageProduct m = new ManageProduct();
        m.setVisible(true);
        dispose();
                 
    }//GEN-LAST:event_manageProductButtonActionPerformed

    private void billingSystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingSystemButtonActionPerformed
        // TODO add your handling code here:
       
        BillingSystem B = new BillingSystem();
        B.setVisible(true);
        dispose();
    }//GEN-LAST:event_billingSystemButtonActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        // TODO add your handling code here:
        
        SignUp s = new SignUp();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BackButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackButtonKeyPressed
        // TODO add your handling code here:
       if((int)evt.getKeyChar()==10)
        {
            this.BackButtonActionPerformed(null);
        }
    }//GEN-LAST:event_BackButtonKeyPressed

    private void createAccountButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createAccountButtonKeyPressed
        // TODO add your handling code here:
        this.createAccountButtonActionPerformed(null);
    }//GEN-LAST:event_createAccountButtonKeyPressed

    private void manageProductButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manageProductButtonKeyPressed
        // TODO add your handling code here:
        this.manageProductButtonActionPerformed(null);
    }//GEN-LAST:event_manageProductButtonKeyPressed

    private void salesHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesHistoryButtonActionPerformed
        // TODO add your handling code here:
        SalesHistory s = new SalesHistory();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salesHistoryButtonActionPerformed

    private void salesHistoryButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salesHistoryButtonKeyPressed
      // TODO add your handling code here:
        if((int)evt.getKeyChar()==10)
        {
            this.salesHistoryButtonActionPerformed(null);
        }
    }//GEN-LAST:event_salesHistoryButtonKeyPressed

    private void billingSystemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billingSystemButtonKeyPressed
        // TODO add your handling code here:
        if((int)evt.getKeyChar()==10)
        {
            this.billingSystemButtonActionPerformed(null);
        }
    }//GEN-LAST:event_billingSystemButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Features.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Features().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton billingSystemButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageProductButton;
    private javax.swing.JButton salesHistoryButton;
    // End of variables declaration//GEN-END:variables
}
