package Frames;


import Database.DbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author labisa
 */
public class ManageProduct extends javax.swing.JFrame {
    
    PreparedStatement pst;
    Connection con =null;
    ResultSet rs;
    private boolean rowSelected = false;

    /**
     * Creates new form ManageProduct
     */
    public ManageProduct() {
        initComponents();
        setTitle("Manage Products");
        this.setLocationRelativeTo(null);
        con = DbConnection.dbConnector();
        this.loadProducts();
        comboProductCategory.setSelectedItem("Custom");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        buttonAddProduct = new javax.swing.JButton();
        buttonUpdateProduct = new javax.swing.JButton();
        buttonReferesh = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        buttonDeleteProduct = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProductCode = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        comboProductCategory = new javax.swing.JComboBox<String>();
        txtProductPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableProducts.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 204))); // NOI18N
        tableProducts.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Food Name", "Food Catagory", "Price"
            }
        ));
        tableProducts.setGridColor(new java.awt.Color(0, 153, 153));
        tableProducts.setSelectionBackground(new java.awt.Color(0, 51, 153));
        tableProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProducts);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, 821, 220));

        buttonAddProduct.setBackground(new java.awt.Color(204, 255, 255));
        buttonAddProduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonAddProduct.setForeground(new java.awt.Color(153, 0, 51));
        buttonAddProduct.setText("Add");
        buttonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddProductActionPerformed(evt);
            }
        });
        buttonAddProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonAddProductKeyPressed(evt);
            }
        });
        getContentPane().add(buttonAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 239, 79, 32));

        buttonUpdateProduct.setBackground(new java.awt.Color(204, 255, 255));
        buttonUpdateProduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonUpdateProduct.setForeground(new java.awt.Color(153, 0, 51));
        buttonUpdateProduct.setText("Update");
        buttonUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateProductActionPerformed(evt);
            }
        });
        buttonUpdateProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonUpdateProductKeyPressed(evt);
            }
        });
        getContentPane().add(buttonUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 239, 79, 32));

        buttonReferesh.setBackground(new java.awt.Color(204, 255, 255));
        buttonReferesh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonReferesh.setForeground(new java.awt.Color(153, 0, 51));
        buttonReferesh.setText("Refresh");
        buttonReferesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefereshActionPerformed(evt);
            }
        });
        buttonReferesh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonRefereshKeyPressed(evt);
            }
        });
        getContentPane().add(buttonReferesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 239, -1, 32));

        buttonBack.setBackground(new java.awt.Color(204, 255, 255));
        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(153, 0, 51));
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        buttonBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonBackKeyPressed(evt);
            }
        });
        getContentPane().add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 239, 79, 32));

        buttonDeleteProduct.setBackground(new java.awt.Color(204, 255, 255));
        buttonDeleteProduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonDeleteProduct.setForeground(new java.awt.Color(153, 0, 51));
        buttonDeleteProduct.setText("Delete");
        buttonDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteProductActionPerformed(evt);
            }
        });
        buttonDeleteProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonDeleteProductKeyPressed(evt);
            }
        });
        getContentPane().add(buttonDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 239, 79, 32));

        jLabel5.setBackground(new java.awt.Color(153, 0, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Products");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 214, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Product Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("              Category");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        txtProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 81, 211, 26));
        getContentPane().add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 116, 211, 26));

        comboProductCategory.setEditable(true);
        comboProductCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboProductCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Set Menu", "Desert", "Bevarage", "Fast Food", "Chinese", "Hot Drinks", "BBQ", "Indian" }));
        comboProductCategory.setToolTipText("");
        comboProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(comboProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 152, 113, 26));

        txtProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 186, 113, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select an Existing Product from the following Table to Delete or Update");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/background.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean tableRowSelected()
    {
        return rowSelected;
    }
    private void txtProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductPriceActionPerformed

    private void buttonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProductActionPerformed
      
        String productCode = this.txtProductCode.getText();
        String productName = this.txtProductName.getText();
        String productCategory = (String)this.comboProductCategory.getSelectedItem();
        String price = this.txtProductPrice.getText();
        int productPrice;
        int flag = 1; //to execute the try block if and only if all the boxes are not empty
        
        //checking for any empty text field
        if(productCode.equals("") || productName.equals("")|| productCategory.equals("") || price.equals(""))
        {
            JOptionPane.showMessageDialog(null, "You Must fill all the Boxes");
            flag = 0;
        }
        else
        {
             if(flag==1)
             {
                try
                {
                     productPrice = Integer.parseInt(price);
                     
                      try 
                    {
                         pst = con.prepareStatement("INSERT INTO Products VALUES (?,?,?,?)");
                         pst.setString(1, productCode);
                         pst.setString(2, productName);
                         pst.setString(3, productCategory);
                         pst.setString(4, price);
                   
                         int i = pst.executeUpdate();
                     
                         if(i>0)
                         {
                           //  JOptionPane.showMessageDialog(null, "Product successfully added!");
                             this.buttonRefereshActionPerformed(null);
                             pst.close();

                         }
                        else
                         {
                             JOptionPane.showMessageDialog(null, "Failed to add Product!");
                             pst.close();
                         }
                    }   
                    catch (Exception e) 
                    {
                          JOptionPane.showMessageDialog(null, "Product Code already exists...!");
                    }
                }
                catch(Exception e)
                {
                     JOptionPane.showMessageDialog(null, "Please Enter a Numerical Value in Price!");
                }
                
            }
         
        }

    }//GEN-LAST:event_buttonAddProductActionPerformed

    private void buttonUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateProductActionPerformed
        // TODO add your handling code here:
        
        if(!this.tableRowSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Selec a Row from the table to Update!");
        }
        else
        {  
             try 
             {
                 pst = con.prepareStatement("update Products set ProductName=\""+txtProductName.getText()+"\""+",ProductCategory=\""+comboProductCategory.getSelectedItem()+"\""+",ProductPrice=\""+txtProductPrice.getText()+"\""+" where ProductCode=\""+txtProductCode.getText()+"\"");
                 pst.executeUpdate();
                 this.buttonRefereshActionPerformed(evt);
                 pst.close();
             } 
             catch (Exception e) 
             {
                 JOptionPane.showMessageDialog(null, e);
             }
        }

        
        
    }//GEN-LAST:event_buttonUpdateProductActionPerformed

    private void comboProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProductCategoryActionPerformed

    private void buttonDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteProductActionPerformed
        // TODO add your handling code here:
         if(!this.tableRowSelected())
         {
            JOptionPane.showMessageDialog(null, "Please Select a Row from the table to Delete!");
            
         }
         else
         {
            
             String productCode = txtProductCode.getText();
             // System.out.println(productCode);
             try
             {
                 String sql = "Delete FROM Products where ProductCode=\""+productCode+"\"";
                 pst = con.prepareStatement(sql);
                 pst.executeUpdate();
                 this.buttonRefereshActionPerformed(null);
                 pst.close();
             }
             catch(Exception e)
             {
                  JOptionPane.showMessageDialog(null,e);
             }
             
         }
    }//GEN-LAST:event_buttonDeleteProductActionPerformed

    private void loadProducts()
    {
         try
        {
            String sql = "Select * From Products order by ProductCode";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            DefaultTableModel model = new DefaultTableModel(new String[]{"Code", "Food Name", "Food Category", "Price"}, 0);

            while(rs.next())
            {
                String col1 = rs.getString("ProductCode");
                String col2 = rs.getString("ProductName");
                String col3 = rs.getString("ProductCategory");
                String col4 = rs.getString("ProductPrice");
                model.addRow(new Object[]{col1, col2, col3, col4});
            }
            tableProducts.setModel(model);
            pst.close();
            rs.close();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        Features f = new Features();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonBackKeyPressed
        // TODO add your handling code here:
        if((int)evt.getKeyChar()==10)
        {
            this.buttonBackActionPerformed(null);
        }
        
    }//GEN-LAST:event_buttonBackKeyPressed

    private void buttonUpdateProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonUpdateProductKeyPressed
        // TODO add your handling code here:
        if((int)evt.getKeyChar()==10)
        {
            this.buttonUpdateProductActionPerformed(null);
        }
        
    }//GEN-LAST:event_buttonUpdateProductKeyPressed

    private void buttonRefereshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefereshActionPerformed
        // TODO add your handling code here:
        
        this.loadProducts();
        txtProductCode.setText("");
        txtProductName.setText("");
        comboProductCategory.setSelectedItem("Custom");
        txtProductPrice.setText("");
        
        this.rowSelected = false;
        txtProductCode.setEditable(true);
    }//GEN-LAST:event_buttonRefereshActionPerformed

    private void tableProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductsMouseClicked
        // TODO add your handling code here:
        
        int selectedRow = tableProducts.getSelectedRow();
        txtProductCode.setEditable(false);
        txtProductCode.setText(tableProducts.getModel().getValueAt(selectedRow, 0).toString());
        txtProductName.setText(tableProducts.getModel().getValueAt(selectedRow, 1).toString());
        comboProductCategory.setSelectedItem(tableProducts.getModel().getValueAt(selectedRow, 2).toString());
        txtProductPrice.setText(tableProducts.getModel().getValueAt(selectedRow, 3).toString());
        this.rowSelected = true;
    }//GEN-LAST:event_tableProductsMouseClicked

    private void buttonAddProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonAddProductKeyPressed
        // TODO add your handling code here:
        
         if((int)evt.getKeyChar()==10)
        {
            this.buttonAddProductActionPerformed(null);
        }
    }//GEN-LAST:event_buttonAddProductKeyPressed

    private void buttonDeleteProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonDeleteProductKeyPressed
        // TODO add your handling code here:
       
         if((int)evt.getKeyChar()==10)
        {
             this.buttonDeleteProductActionPerformed(null);
        }
    }//GEN-LAST:event_buttonDeleteProductKeyPressed

    private void buttonRefereshKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonRefereshKeyPressed
        // TODO add your handling code here: 
         if((int)evt.getKeyChar()==10)
        {
            this.buttonRefereshActionPerformed(null);
        }
    }//GEN-LAST:event_buttonRefereshKeyPressed

    private void txtProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddProduct;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonDeleteProduct;
    private javax.swing.JButton buttonReferesh;
    private javax.swing.JButton buttonUpdateProduct;
    private javax.swing.JComboBox<String> comboProductCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProducts;
    private javax.swing.JTextField txtProductCode;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    // End of variables declaration//GEN-END:variables
}
